### ISSUE TITLE
RSS 비디오 컨텐츠

### ISSUE THREAD

**Issue by L2zz** [joy-team/d2-campus-fest#1]
RSS 에서 video가 thumbnail 느낌으로 이미지만 나타납니다. 
해결방안이 있을까요?

```
현재 적용 rss
https://rss.app/feeds/GwCARMIg7mCvYdBb.xml
```

**Comment by guswh11** [comment]
http://fetchrss.com/
이 사이트에서 url을 얻는 것이 도움이 될 것 같습니다
video도 적용 되고 사진이 여러 장인 경우도 지원하는 것으로 보여요

**Comment by L2zz** [comment]
감사합니다! 확인해보니 가능한것 같습니다
