### ISSUE TITLE
Viewpager와 Cardview 레이아웃 

### ISSUE THREAD

**Issue by guswh11** [joy-team/d2-campus-fest#3]
현재 item_feed.xml에 프로필 사진과 아이디가 들어가는 레이아웃, 카드뷰가 들어가는 viewpager가 존재합니다. 사용자가 피드를 슬라이드 할 때 프로필은 viewpager와 별개로 움직이지 않고 고정시키고, 글만 넘어가게끔 카드뷰와 프로필을 분리해 놓았습니다. 

현재는 카드뷰의 radius를 없애 거의 직각으로 보이게끔 해놨고, 프로필 레이아웃과 카드뷰가 인접해 있어 두 레이아웃이 분리된 것처럼 보이지는 않는 상황입니다. 
하지만 만약 전체 화면에 색깔이 들어가면 두 레이아웃이 분리된 것이 매우 티가 나게 됩니다.
또, 피드 테두리를 둥글게 하고 싶다면 레이아웃에 수정이 필요해 보입니다. 

여기서 몇 가지 대체 방안이 있는데, 
1. 레이아웃 배치는 그대로 두고 background로 둥근 모서리를 넣어 준다. 
2. 카드뷰 안에 viewpager를 넣어 프로필 레이아웃 또한 카드뷰 안에 속하게 한다
3. 레이아웃은 그대로 두고 전체 화면 배경색 또한 두지 않는다. (색깔x, 둥근 모서리 x) 
어느 것이 나을지 의견을 묻고 싶습니다.

**Comment by L2zz** [comment]
제 핸드폰으로 테스트 했을 때는 
프로필과 카드뷰에 width자체가 달라 확연하게 구분되보여
2번 선택지로 가는게 좋아보입니다.
