### ISSUE TITLE
Rss class 내부의 String 데이터 

### ISSUE THREAD

**Issue by guswh11** [joy-team/d2-campus-fest#4]
1. 사용자 아이디 앞에 @가 붙음
2. Article의 pubDate 형식 
3. 글 내용이 존재하지 않을 경우 Article의 title이 new post로 나옴 

이 부분에 대해 수정이 필요해 보입니다

**Comment by L2zz** [comment]
2번 항목관련해서 
```
2019년 7월 16일 화요일 13:06
```
형태로 출력할 수 있도록 우선 변경해 두었고 보다 보기 좋은 포맷이 존재한다면 제안해주세요 😃
