### ISSUE TITLE
Cardview 나열 순서

### ISSUE THREAD

**Issue by L2zz** [joy-team/d2-campus-fest#5]
현재 Card view가 앱을 열때마다 순서가 달라지는 현상이 발생하고 있는 것 같습니다.

<div>
<img src="https://user-images.githubusercontent.com/37107066/61839200-a7e46980-aec7-11e9-83de-fe881ee4aa03.png" width="40%" height="40%">
<img src="https://user-images.githubusercontent.com/37107066/61839202-a87d0000-aec7-11e9-8a02-186c4879283a.png" width="40%" height="40%">
</div>

**Comment by guswh11** [comment]
확인했습니다! 현재 작업중인 복수의 사진 및 동영상 불러오기 작업이 완료되면, 최근 순으로 정렬하는 작업이 필요할 것 같습니다

**Comment by guswh11** [comment]
해결했습니다.
